# Generated by Django 2.0.2 on 2018-04-22 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20180403_2025'),
        ('secretary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.Patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='procedure',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
