# Generated by Django 2.0.2 on 2018-04-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0002_auto_20180422_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='address1',
            field=models.CharField(default='not provided', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='address2',
            field=models.CharField(default='not provided', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='city',
            field=models.CharField(default='not provided', max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(default='not provided', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(default='not provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='not provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone_num',
            field=models.CharField(default='not provided', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='procedure',
            field=models.CharField(default='not provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.CharField(default='not provided', max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='zip_code',
            field=models.CharField(default='not provided', max_length=20),
        ),
    ]
