# Generated by Django 2.0.2 on 2018-04-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20180403_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user_id',
            field=models.CharField(default='lemon', max_length=12),
            preserve_default=False,
        ),
    ]
