# Generated by Django 2.0.2 on 2018-04-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
