# Generated by Django 2.0.2 on 2018-04-17 20:21

from django.db import migrations

def add_patients(apps, schema_editor):
    Doctor = apps.get_model('doctor', 'Doctor')
    doctor = Doctor(name='Ani')
    doctor.save()

    Patient = apps.get_model('doctor', 'Patient')
    patient = Patient(first_name='Ani',
                      last_name='Park',
                      doctor_id=Doctor.objects.get(pk=1))
    patient.save()


    patient = Patient(first_name='Anna',
                      last_name='Simpson',
                      doctor_id=Doctor.objects.get(pk=1))
    patient.save()


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_procedure'),
    ]
    operations = [
        migrations.RunPython(add_patients)
    ]